---
- hosts: dbservers
  gather_facts: False
  become_user: postgres
  become: True
  tasks:
    - name: create radioco database user
      postgresql_user:
        name: "{{ database.user }}"
        password: "{{ database.password }}"

    - name: create radioco database
      postgresql_db:
        name: "{{ database.name }}"
        owner: "{{ database.user }}"

