---
- hosts: appservers
  gather_facts: no
  tasks:
  - name: install requirements
    become: yes
    apt: name={{ item }}
    with_items:
      - git
      - libjpeg-dev
      - libpq-dev
      - nodejs
      - python-pip
      - python-virtualenv
      - python3-dev
      - supervisor

- hosts: dbserver
  gather_facts: no
  tasks:
  - name: install requirements
    become: yes
    apt: name={{ item }}
    with_items:
        - python-psycopg2
