---
- hosts: appservers
  gather_facts: FalsFalse
  tasks:
  - name: install requirements
    become: True
    apt:
      name:
        - git
        - libjpeg-dev
        - libpq-dev
        - nodejs
        - python-pip
        - python-virtualenv
        - python3-dev
        - supervisor

- hosts: dbserver
  gather_facts: False
  tasks:
  - name: install requirements
    become: True
    apt:
      name: python-psycopg2
