---
- hosts: appservers
  tasks:
  - name: install requirements
    become: yes
    apt: name={{ item }}
    with_items:
      - git
      - libjpeg-dev
      - libpq-dev
      - nodejs
      - python-dev
      - python-pip
      - python-psycopg2
      - python-virtualenv
      - supervisor
- hosts: dbserver
  tasks:
  - name: install requirements
    become: yes
    apt: name={{ item }}
    with_items:
        - python-psycopg2
