---
- name: run buildout
  command: ./bin/buildout chdir={{workdir}}
  notify:
    - run database migration
    - run bower install
    - run collectstatic
    - restart supervisord process

- name: run database migration
  command: ./bin/radioco-admin migrate chdir={{workdir}}

- name: run bower install
  command: ./bin/radioco-admin bower install chdir={{workdir}}

- name: run collectstatic
  command: ./bin/radioco-admin collectstatic --noinput --clear chdir={{workdir}}

- name: reload nginx
  become: yes
  service:
    name: nginx
    state: reloaded

- name: restart supervisord process
  become: yes
  supervisorctl:
    name: "radioco_{{ branch }}"
    state: restarted
